services:
    tacitus89.homepage.listener:
        class: tacitus89\homepage\event\listener
        arguments:
            - @request
        tags:
            - { name: event.listener }

    tacitus89.homepage.index:
        class: tacitus89\homepage\controller\index
        arguments:
            - @config
            - @service_container
            - @controller.helper
            - @template
            - @user
            - @cache.driver
            - %core.root_path%
            - %core.php_ext%

    tacitus89.homepage.page:
        class: tacitus89\homepage\entity\page
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @dbal.conn

    tacitus89.homepage.category:
            class: tacitus89\homepage\entity\category
            scope: prototype # scope MUST be prototype for this to work!
            arguments:
                - @dbal.conn

    tacitus89.homepage.topic:
            class: tacitus89\homepage\entity\topic
            scope: prototype # scope MUST be prototype for this to work!
            arguments:
                - @dbal.conn

    tacitus89.homepage.categories:
            class: tacitus89\homepage\operators\categories
            arguments:
                - @service_container
                - @dbal.conn

    tacitus89.homepage.topics:
                class: tacitus89\homepage\operators\topics
                arguments:
                    - @service_container
                    - @dbal.conn

    tacitus89.homepage.widgets:
                class: tacitus89\homepage\operators\widgets
                arguments:
                    - @service_container
                    - @dbal.conn
                    - @template
                    - @user
                    - %core.root_path%
                    - %core.php_ext%